const TV_ITEMS = [
    {
        title: 'Amor Perfeito',
        original_title: 'Amor Perfeito',
        release_date: '2023-03-20',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/aOPhyvHDauWFuc3rthpHArCNyrm.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/azWBrlovNOOdy0eQYEe9BoiROoN.jpg',
        vote: 6,
    },
    {
        title: 'Terra e Paixão',
        original_title: 'Terra e Paixão',
        release_date: '2023-05-08',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/voaKRrYExZNkf1E4FZExU7fTd8w.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/aWPhMZ0P2DyfWB7k5NXhGHSZHGC.jpg',
        vote: 5.3,
    },
    {
        title: 'Faltu',
        original_title: 'Faltu',
        release_date: '2022-11-02',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/lgyFuoXs7GvKJN0mNm7z7OMOFuZ.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/t2rAdgjSh0WYbXzdOB5zTDqzdCI.jpg',
        vote: 5.1,
    },
    {
        title: 'Invasión Secreta',
        original_title: 'Secret Invasion',
        release_date: '2023-06-21',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/7SAIwUnkDsRjLNGQcsxyVqQny7D.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/57clBMPX25NNO6nmDw3TV3zQaQE.jpg',
        vote: 7.9,
    },
    {
        title: 'Al rojo vivo',
        original_title: 'Al rojo vivo',
        release_date: '2011-01-10',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/ag6PmoBxkF2s1uY3An618NCEt3g.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/69Jblm3seQgiPuPQMrJqg9Nxhaz.jpg',
        vote: 2.9,
    },
    {
        title: 'Pânico Jovem Pan',
        original_title: 'Pânico Jovem Pan',
        release_date: '2021-01-26',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/3fEP3SfnLKw9QuuQW72P3b9nekE.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/5sZvnK6hd3NC8MSI70avNzFVMGF.jpg',
        vote: 5.5,
    },
    {
        title: 'Imlie',
        original_title: 'इमली',
        release_date: '2020-11-16',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/sltUDXvpDZK3aVIdtkbImhcJv8t.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/i8NGdMIyZnGNpSHLDtpPwYXidPe.jpg',
        vote: 4.7,
    },
    {
        title: 'Sólo Confía',
        original_title: 'Vai na Fé',
        release_date: '2023-01-16',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/6QNohzb7YUJ6eWZkXAYU8KGIq.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/xYiI6QEZvx8Z4La1oHvApyZHpOU.jpg',
        vote: 7.5,
    },
    {
        title: 'Dirty Linen',
        original_title: 'Dirty Linen',
        release_date: '2023-01-23',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/aoAZgnmMzY9vVy9VWnO3U5PZENh.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/mAJ84W6I8I272Da87qplS2Dp9ST.jpg',
        vote: 4.7,
    },
    {
        title: 'Flor Sem Tempo',
        original_title: 'Flor Sem Tempo',
        release_date: '2023-01-30',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/bclnfDXvx7UydFSk83B258vRRvI.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/5MkBAawsj7O9zitVtzMXagyrIBw.jpg',
        vote: 10,
    },
    {
        title: 'Voltes V: Legacy',
        original_title: 'Voltes V: Legacy',
        release_date: '2023-05-08',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/8Sio0GDDIP0okgG4dez1yuKQBPW.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/fEP2Sha3PXJnAcoGOjr5oybq44Q.jpg',
        vote: 4.4,
    },
];

const MOVIES_ITEMS = [
    {
        title: 'Rápidos y furiosos X',
        original_title: 'Fast X',
        release_date: '2023-05-19',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/3P9QvWVN02Etn4kYGC702WVoXEb.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/e2Jd0sYMCe6qvMbswGQbM0Mzxt0.jpg',
        vote: 7.3,
    },
    {
        title: 'Misión de rescate 2',
        original_title: 'Extraction 2',
        release_date: '2023-06-16',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/jT0Eyfw0VXlnk8sMKfyFiKj8UsK.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/fhquRW28vRZHr26orSaFFnhYIA0.jpg',
        vote: 7.6,
    },
    {
        title: 'Spider-Man: A través del Spider-Verso',
        original_title: 'Spider-Man: Across the Spider-Verse',
        release_date: '2023-06-02',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/qqXTerrQYwg9pIMhb1GFbxa3WUz.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/nGxUxi3PfXDRm7Vg95VBNgNM8yc.jpg',
        vote: 8.6,
    },
    {
        title: 'John Wick 4',
        original_title: 'John Wick: Chapter 4',
        release_date: '2023-03-24',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/mj2Z9HnRSIEk3n7yVPoOY4Uzzfh.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/fgw4rFs4XMWdJTWp1eMacHKQqbZ.jpg',
        vote: 7.9,
    },
    {
        title: 'Super Mario Bros. La película',
        original_title: 'The Super Mario Bros. Movie',
        release_date: '2023-04-05',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/zNKs1T0VZuJiVuhuL5GSCNkGdxf.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/nniZPBIfrep9wbx0l1529RHXeD8.jpg',
        vote: 7.8,
    },
    {
        title: 'Transformers: El despertar de las bestias',
        original_title: 'Transformers: Rise of the Beasts',
        release_date: '2023-06-09',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/yu24fXpro7jx4XFlgEWwElW1kgW.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/qWQSnedj0LCUjWNp9fLcMtfgadp.jpg',
        vote: 7.2,
    },
    {
        title: 'Culpa mía',
        original_title: 'Culpa mía',
        release_date: '2023-06-08',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/gp31EwMH5D2bftOjscwkgTmoLAB.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/pNOccytgkGuyofTLmh1sqEfTJuE.jpg',
        vote: 8.3,
    },
    {
        title: 'Elementos',
        original_title: 'Elemental',
        release_date: '2023-07-14',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/3RuphN7wadSCoIhD7u1gkLkx634.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/cSYLX73WskxCgvpN3MtRkYUSj1T.jpg',
        vote: 7.5,
    },
    {
        title: 'Guardianes de la Galaxia volumen 3',
        original_title: 'Guardians of the Galaxy Vol. 3',
        release_date: '2023-05-04',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/6GkKzdNosVAL7UGgwTtCHSxLQ67.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg',
        vote: 8.1,
    },
    {
        title: 'Flash',
        original_title: 'The Flash',
        release_date: '2023-06-16',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/x9Qc86JEyYkAKsdzjDpS5kbaAB7.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/fEe2csLOUsTyaLdCccVJfFeJzhx.jpg',
        vote: 6.7,
    },
    {
        title: 'Avatar: El camino del agua',
        original_title: 'Avatar: The Way of Water',
        release_date: '2022-12-16',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/bqOqQ2Tawum3eHKNrc94P4EeaZB.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/4pNlHx6ytdYBDs94PgcS0wQkbc4.jpg',
        vote: 7.7,
    },
    {
        title: 'La sirenita',
        original_title: 'The Little Mermaid',
        release_date: '2023-05-26',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/mdszPVnIY7cWgbgJ8zbwu1PiU5V.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/ribiMu3iINPxDkofErPxe8jQ8L0.jpg',
        vote: 6.2,
    },
    {
        title: 'Demonio negro',
        original_title: 'The Black Demon',
        release_date: '2023-07-06',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/ohxEF8mZb7eVeUZonUk60BAVN5u.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/9t0tJXcOdWwwxmGTk112HGDaT0Q.jpg',
        vote: 6.3,
    },
    {
        title: 'El Pacto (The Covenant)',
        original_title: "Guy Ritchie's The Covenant",
        release_date: '2023-06-02',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/siO8SNMEuyo25jHO2dqQxY4gWxZ.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/b8tX15xHPai3bYeKYgAZikANTGl.jpg',
        vote: 7.8,
    },
    {
        title: 'Evil Dead: El despertar',
        original_title: 'Evil Dead Rise',
        release_date: '2023-04-21',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/ioMtng0qHbwNjR1fuxYZsRf1kjm.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/sFGENDTUNOuDbVufxksCkrDtuaT.jpg',
        vote: 7,
    },
    {
        title: 'Ant-Man and the Wasp: Quantumania',
        original_title: 'Ant-Man and the Wasp: Quantumania',
        release_date: '2023-02-17',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/lKHy0ntGPdQeFwvNq8gK1D0anEr.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/gMJngTNfaqCSCqGD4y8lVMZXKDn.jpg',
        vote: 6.5,
    },
    {
        title: 'Titanic',
        original_title: 'Titanic',
        release_date: '1998-01-08',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/rBTJZrf5UWaxzg5YJd2eqpeaSvm.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/rzdPqYx7Um4FUZeD8wpXqjAUcEm.jpg',
        vote: 7.9,
    },
    {
        title: 'A través del mar',
        original_title: 'A través del mar',
        release_date: '2023-06-23',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/ykS1waU5GsEjPbiNnsHG2bl9QvS.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/mmSSn8Yn3GbJv9MsSnD4J1LnN9l.jpg',
        vote: 6.7,
    },
    {
        title: 'Indiana Jones y el dial del destino',
        original_title: 'Indiana Jones and the Dial of Destiny',
        release_date: '2023-06-28',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/3Sj5ubQ0BLXd6JuECq52Ira8Oor.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/zPcuuhwZFDzBTc66wtrLZ2qX5y4.jpg',
        vote: 6.5,
    },
    {
        title: 'Sisu',
        original_title: 'Sisu',
        release_date: '2023-04-28',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/t9VXZkgcxpIwfPUKAWOOONs0vHv.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/94TIUEhuwv8PhdIADEvSuwPljS5.jpg',
        vote: 7.3,
    },
];

export default [...MOVIES_ITEMS, ...TV_ITEMS];
