const TV_ITEMS = [
    {
        title: 'Amor Perfeito',
        original_title: 'Amor Perfeito',
        release_date: '2023-03-20',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/aOPhyvHDauWFuc3rthpHArCNyrm.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/azWBrlovNOOdy0eQYEe9BoiROoN.jpg',
        vote: 6,
    },
    {
        title: 'Terra e Paixão',
        original_title: 'Terra e Paixão',
        release_date: '2023-05-08',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/voaKRrYExZNkf1E4FZExU7fTd8w.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/aWPhMZ0P2DyfWB7k5NXhGHSZHGC.jpg',
        vote: 5.3,
    },
    {
        title: 'Faltu',
        original_title: 'Faltu',
        release_date: '2022-11-02',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/lgyFuoXs7GvKJN0mNm7z7OMOFuZ.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/t2rAdgjSh0WYbXzdOB5zTDqzdCI.jpg',
        vote: 5.1,
    },
    {
        title: 'Invasión Secreta',
        original_title: 'Secret Invasion',
        release_date: '2023-06-21',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/7SAIwUnkDsRjLNGQcsxyVqQny7D.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/57clBMPX25NNO6nmDw3TV3zQaQE.jpg',
        vote: 7.9,
    },
    {
        title: 'Pânico Jovem Pan',
        original_title: 'Pânico Jovem Pan',
        release_date: '2021-01-26',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/3fEP3SfnLKw9QuuQW72P3b9nekE.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/5sZvnK6hd3NC8MSI70avNzFVMGF.jpg',
        vote: 5.5,
    },
    {
        title: 'Imlie',
        original_title: 'इमली',
        release_date: '2020-11-16',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/sltUDXvpDZK3aVIdtkbImhcJv8t.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/i8NGdMIyZnGNpSHLDtpPwYXidPe.jpg',
        vote: 4.7,
    },
    {
        title: 'Sólo Confía',
        original_title: 'Vai na Fé',
        release_date: '2023-01-16',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/6QNohzb7YUJ6eWZkXAYU8KGIq.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/xYiI6QEZvx8Z4La1oHvApyZHpOU.jpg',
        vote: 7.5,
    },
    {
        title: 'Dirty Linen',
        original_title: 'Dirty Linen',
        release_date: '2023-01-23',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/aoAZgnmMzY9vVy9VWnO3U5PZENh.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/mAJ84W6I8I272Da87qplS2Dp9ST.jpg',
        vote: 4.7,
    },
    {
        title: 'Flor Sem Tempo',
        original_title: 'Flor Sem Tempo',
        release_date: '2023-01-30',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/bclnfDXvx7UydFSk83B258vRRvI.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/5MkBAawsj7O9zitVtzMXagyrIBw.jpg',
        vote: 10,
    },
    {
        title: 'Voltes V: Legacy',
        original_title: 'Voltes V: Legacy',
        release_date: '2023-05-08',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/8Sio0GDDIP0okgG4dez1yuKQBPW.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/fEP2Sha3PXJnAcoGOjr5oybq44Q.jpg',
        vote: 4.4,
    },
    {
        title: 'Demain nous appartient',
        original_title: 'Demain nous appartient',
        release_date: '2017-07-17',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/3uU5uJzOX7xe7mn7YKpBM9oiEZO.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/9TXcHOeCsM8W3ZKKIKjdYUsRSeq.jpg',
        vote: 6.3,
    },

    {
        title: 'From',
        original_title: 'From',
        release_date: '2022-02-20',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/pnrv8tfOcWxu4CrB8N7xK0jYJsR.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/q3UGWifvIpdey1T2efX4dSmbZpU.jpg',
        vote: 8.3,
    },
    {
        title: 'Un si grand soleil',
        original_title: 'Un si grand soleil',
        release_date: '2018-08-27',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/v4r70Z5id8eHFCxrfBOtRgu6wLr.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/rj3jBAZwPiOgkwAy1205MAgLahj.jpg',
        vote: 7.2,
    },
    {
        title: 'The Walking Dead: Dead City',
        original_title: 'The Walking Dead: Dead City',
        release_date: '2023-06-18',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/wq3vuQzQgbS83zX3malAFWMsSwX.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/xqIhUVrfFVZIHVyj6Rf7zCN8n3l.jpg',
        vote: 8.5,
    },
    {
        title: 'Silo',
        original_title: 'Silo',
        release_date: '2023-05-04',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/mx3n0DbDhwEClnoOjtHvPUKmNtQ.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/1V4SPkV3bQvl85zK4FqwTzdfBs4.jpg',
        vote: 8.3,
    },
    {
        title: 'The Noite com Danilo Gentili',
        original_title: 'The Noite com Danilo Gentili',
        release_date: '2014-03-10',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/iEJfqL1yKFY7Wme00ssLgocqExo.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/lIEput5jpJm1I0Yz3pXtWBs4X22.jpg',
        vote: 5,
    },

    {
        title: 'The Good Doctor',
        original_title: 'The Good Doctor',
        release_date: '2017-09-25',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/eCvGVqmxXcNvLMJxLAJeBZ2cUnM.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/6Ys6koNajP5ld9EIMfOSQrRquki.jpg',
        vote: 8.5,
    },
    {
        title: 'Anatomía según Grey',
        original_title: "Grey's Anatomy",
        release_date: '2005-03-27',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/jPzW61WlkyHVdvm8dCQZveTvmgW.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/jNPEKkFKMl7UCw4kbNUkXZNyhna.jpg',
        vote: 8.3,
    },

    {
        title: 'The Flash',
        original_title: 'The Flash',
        release_date: '2014-10-07',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/7ci4qqkBJorLxSBwTj28vwh0bU.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/gNPWlhUXhyWiHv9qxr57tvT0WwS.jpg',
        vote: 7.8,
    },
    {
        title: 'Superman y Lois',
        original_title: 'Superman & Lois',
        release_date: '2021-02-23',
        type: 'TV',
        poster: 'https://image.tmdb.org/t/p/original/hlMO1juHPuaiyL27BDLUcAvxmqq.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/9OGmUZSkqBMZeNPjEjIgr3HbKs2.jpg',
        vote: 8.1,
    },
];

const MOVIES_ITEMS = [
    {
        title: 'Rápidos y furiosos X',
        original_title: 'Fast X',
        release_date: '2023-05-19',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/3P9QvWVN02Etn4kYGC702WVoXEb.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/e2Jd0sYMCe6qvMbswGQbM0Mzxt0.jpg',
        vote: 7.3,
    },
    {
        title: 'Misión de rescate 2',
        original_title: 'Extraction 2',
        release_date: '2023-06-16',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/jT0Eyfw0VXlnk8sMKfyFiKj8UsK.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/fhquRW28vRZHr26orSaFFnhYIA0.jpg',
        vote: 7.6,
    },
    {
        title: 'Spider-Man: A través del Spider-Verso',
        original_title: 'Spider-Man: Across the Spider-Verse',
        release_date: '2023-06-02',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/qqXTerrQYwg9pIMhb1GFbxa3WUz.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/nGxUxi3PfXDRm7Vg95VBNgNM8yc.jpg',
        vote: 8.6,
    },
    {
        title: 'John Wick 4',
        original_title: 'John Wick: Chapter 4',
        release_date: '2023-03-24',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/mj2Z9HnRSIEk3n7yVPoOY4Uzzfh.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/fgw4rFs4XMWdJTWp1eMacHKQqbZ.jpg',
        vote: 7.9,
    },
    {
        title: 'Super Mario Bros. La película',
        original_title: 'The Super Mario Bros. Movie',
        release_date: '2023-04-05',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/zNKs1T0VZuJiVuhuL5GSCNkGdxf.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/nniZPBIfrep9wbx0l1529RHXeD8.jpg',
        vote: 7.8,
    },
    {
        title: 'Transformers: El despertar de las bestias',
        original_title: 'Transformers: Rise of the Beasts',
        release_date: '2023-06-09',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/yu24fXpro7jx4XFlgEWwElW1kgW.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/qWQSnedj0LCUjWNp9fLcMtfgadp.jpg',
        vote: 7.2,
    },
    {
        title: 'Culpa mía',
        original_title: 'Culpa mía',
        release_date: '2023-06-08',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/gp31EwMH5D2bftOjscwkgTmoLAB.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/pNOccytgkGuyofTLmh1sqEfTJuE.jpg',
        vote: 8.3,
    },
    {
        title: 'Elementos',
        original_title: 'Elemental',
        release_date: '2023-07-14',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/3RuphN7wadSCoIhD7u1gkLkx634.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/cSYLX73WskxCgvpN3MtRkYUSj1T.jpg',
        vote: 7.5,
    },
    {
        title: 'Guardianes de la Galaxia volumen 3',
        original_title: 'Guardians of the Galaxy Vol. 3',
        release_date: '2023-05-04',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/6GkKzdNosVAL7UGgwTtCHSxLQ67.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg',
        vote: 8.1,
    },
    {
        title: 'Flash',
        original_title: 'The Flash',
        release_date: '2023-06-16',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/x9Qc86JEyYkAKsdzjDpS5kbaAB7.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/fEe2csLOUsTyaLdCccVJfFeJzhx.jpg',
        vote: 6.7,
    },
    {
        title: 'Avatar: El camino del agua',
        original_title: 'Avatar: The Way of Water',
        release_date: '2022-12-16',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/bqOqQ2Tawum3eHKNrc94P4EeaZB.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/4pNlHx6ytdYBDs94PgcS0wQkbc4.jpg',
        vote: 7.7,
    },
    {
        title: 'La sirenita',
        original_title: 'The Little Mermaid',
        release_date: '2023-05-26',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/mdszPVnIY7cWgbgJ8zbwu1PiU5V.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/ribiMu3iINPxDkofErPxe8jQ8L0.jpg',
        vote: 6.2,
    },
    {
        title: 'Indiana Jones y el dial del destino',
        original_title: 'Indiana Jones and the Dial of Destiny',
        release_date: '2023-06-28',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/3Sj5ubQ0BLXd6JuECq52Ira8Oor.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/zPcuuhwZFDzBTc66wtrLZ2qX5y4.jpg',
        vote: 6.5,
    },
    {
        title: 'Demonio negro',
        original_title: 'The Black Demon',
        release_date: '2023-07-06',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/ohxEF8mZb7eVeUZonUk60BAVN5u.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/9t0tJXcOdWwwxmGTk112HGDaT0Q.jpg',
        vote: 6.3,
    },
    {
        title: 'El Pacto (The Covenant)',
        original_title: "Guy Ritchie's The Covenant",
        release_date: '2023-06-02',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/siO8SNMEuyo25jHO2dqQxY4gWxZ.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/b8tX15xHPai3bYeKYgAZikANTGl.jpg',
        vote: 7.8,
    },
    {
        title: 'Evil Dead: El despertar',
        original_title: 'Evil Dead Rise',
        release_date: '2023-04-21',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/ioMtng0qHbwNjR1fuxYZsRf1kjm.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/sFGENDTUNOuDbVufxksCkrDtuaT.jpg',
        vote: 7,
    },
    {
        title: 'Ant-Man and the Wasp: Quantumania',
        original_title: 'Ant-Man and the Wasp: Quantumania',
        release_date: '2023-02-17',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/lKHy0ntGPdQeFwvNq8gK1D0anEr.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/gMJngTNfaqCSCqGD4y8lVMZXKDn.jpg',
        vote: 6.5,
    },
    {
        title: 'Titanic',
        original_title: 'Titanic',
        release_date: '1998-01-08',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/rBTJZrf5UWaxzg5YJd2eqpeaSvm.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/rzdPqYx7Um4FUZeD8wpXqjAUcEm.jpg',
        vote: 7.9,
    },
    {
        title: 'A través del mar',
        original_title: 'A través del mar',
        release_date: '2023-06-23',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/ykS1waU5GsEjPbiNnsHG2bl9QvS.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/mmSSn8Yn3GbJv9MsSnD4J1LnN9l.jpg',
        vote: 6.7,
    },
    {
        title: 'Sisu',
        original_title: 'Sisu',
        release_date: '2023-04-28',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/t9VXZkgcxpIwfPUKAWOOONs0vHv.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/94TIUEhuwv8PhdIADEvSuwPljS5.jpg',
        vote: 7.3,
    },
    {
        title: '¡Shazam! La furia de los dioses',
        original_title: 'Shazam! Fury of the Gods',
        release_date: '2023-03-17',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/igFLHxab9zG0M89OmEpnOM6TPXn.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/hUVJVsKP7Fu2kGdWXZKbEAXRMNM.jpg',
        vote: 6.7,
    },
    {
        title: 'Lórax: En Busca De La Trúfula Perdida',
        original_title: 'The Lorax',
        release_date: '2012-03-30',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/bkrgpEDmRebGDbhX1gPC96Kvljl.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/sWulI556AJZ1DAQnxyAvnAAY6nd.jpg',
        vote: 6.5,
    },
    {
        title: 'Encanto',
        original_title: 'Encanto',
        release_date: '2021-11-26',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/4JCyBaUJmMgmnDkLiOI8P3tDpqS.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/wXFxYH14m3JdsCpoWDyqgDF7vVw.jpg',
        vote: 7.6,
    },
    {
        title: 'It (Eso)',
        original_title: 'It',
        release_date: '2017-09-08',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/sSrj4lnhrb113DOPEPTaO2jaDk3.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/tcheoA2nPATCm2vvXw2hVQoaEFD.jpg',
        vote: 7.2,
    },
    {
        title: 'El exorcista del Papa',
        original_title: "The Pope's Exorcist",
        release_date: '2023-04-05',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/4n7HJ322ARRWytwxLKEZi0mIrYE.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/bJFKGpUbSFSoXcIZcAgtAi3rtc7.jpg',
        vote: 7.2,
    },
    {
        title: 'Spider-Man: Un Nuevo Universo',
        original_title: 'Spider-Man: Into the Spider-Verse',
        release_date: '2018-12-21',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/xRMZikjAHNFebD1FLRqgDZeGV4a.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/1ntePsIqeklfmrQJqZPncCydsqY.jpg',
        vote: 8.4,
    },
    {
        title: 'Gato con Botas: El último deseo',
        original_title: 'Puss in Boots: The Last Wish',
        release_date: '2022-12-21',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/b5Jb7GoQaqIXy4VEdnQa0UrQZI.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/jr8tSoJGj33XLgFBy6lmZhpGQNu.jpg',
        vote: 8.3,
    },
    {
        title: 'Los Caballeros del Zodiaco: Saint Seiya - El inicio',
        original_title: 'Knights of the Zodiac',
        release_date: '2023-05-26',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/zqhO44oc0pWM32seJeXMcjPLvwV.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/u17VLZqWFbeJsj1HpvB6QOOHvlC.jpg',
        vote: 6.6,
    },
    {
        title: 'Terremoto: La Falla De San Andrés',
        original_title: 'San Andreas',
        release_date: '2015-06-26',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/uC4uhJuyOxZQhMcJoKQWbe667Sx.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/zcySy6dnSmyqiichtDgO7AEeZoq.jpg',
        vote: 6.2,
    },
    {
        title: 'El Conjuro 3: El Diablo me Obligó a Hacerlo',
        original_title: 'The Conjuring: The Devil Made Me Do It',
        release_date: '2021-06-04',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/ghMQALCyytc6W0wlOlMIKiMSRKV.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/qi6Edc1OPcyENecGtz8TF0DUr9e.jpg',
        vote: 7.5,
    },
    {
        title: 'Creed III',
        original_title: 'Creed III',
        release_date: '2023-03-03',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/fcFMd3HdyX7r5gtFwVnn2qr5Yhq.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/5i6SjyDbDWqyun8klUuCxrlFbyw.jpg',
        vote: 7.2,
    },
    {
        title: 'Paw Patrol: La Película',
        original_title: 'PAW Patrol: The Movie',
        release_date: '2021-08-27',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/fOYt5TfJKHHz0hFY37kSXKvEdf7.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/a17F3zXnmuwqxfiDa46mtlosjrv.jpg',
        vote: 7.4,
    },
    {
        title: 'La noche del demonio: La última llave',
        original_title: 'Insidious: The Last Key',
        release_date: '2018-01-05',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/d5l0baYosvDH4HCEc6O7h1QgAp9.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/PwI3EfasE9fVuXsmMu9ffJh0Re.jpg',
        vote: 6.3,
    },
    {
        title: 'Garfield',
        original_title: 'Garfield',
        release_date: '2004-09-01',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/pMQKL3Dx40au9e172ARVUWsT4qH.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/5bJG7HaFogEqPEjRbOs8S0Szb4x.jpg',
        vote: 5.7,
    },
    {
        title: "Flamin' Hot: El sabor que cambió la historia",
        original_title: "Flamin' Hot",
        release_date: '2023-06-09',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/gHghpc8mhVi7P5YilodDt7NLEtU.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/lIbSfonygV4nS09jy80QKGGcYva.jpg',
        vote: 8.2,
    },
    {
        title: 'Asesinatos Accidentales: Unas Vacaciones Para Morir',
        original_title: "Accident Man: Hitman's Holiday",
        release_date: '2023-05-20',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/b5otfV0DzbtLlPIoZTpJd7pkWh8.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/fIlmxFWplRXTACPoGnOuwIwzBuF.jpg',
        vote: 6.5,
    },
    {
        title: 'Ghosteado',
        original_title: 'Ghosted',
        release_date: '2023-04-21',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/zSw2JeQ03GivcS4VKJmWK5sYi1F.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/8NFDAkEFbKVQKYIh61JAxO78yFa.jpg',
        vote: 7.1,
    },
    {
        title: 'Corazones De Hierro',
        original_title: 'Fury',
        release_date: '2015-01-09',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/kbtH5G8L8REzy72LkLmKYoBVaGv.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/kdbLf3aTQsEXqYlH9vA4fzmnSFz.jpg',
        vote: 7.5,
    },
    {
        title: 'Hazme el favor',
        original_title: 'No Hard Feelings',
        release_date: '2023-06-23',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/hKlpYtDLBtJEvYVvaUIq39Gh6rI.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/cKE9qZqYtF4jimf0GFOqKfy7NEU.jpg',
        vote: 6.4,
    },
    {
        title: 'Spider-Man: Sin camino a casa',
        original_title: 'Spider-Man: No Way Home',
        release_date: '2021-12-16',
        type: 'MOVIE',
        poster: 'https://image.tmdb.org/t/p/original/miZFgV81xG324rpUknQX8dtXuBl.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg',
        vote: 8,
    },
];

export default [...MOVIES_ITEMS, ...TV_ITEMS];
